org: snowcait
app: serverless-twitter
service: serverless-twitter

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  memorySize: 128

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: GET
          path: /hello
