org: snowcait
app: serverless-twitter
service: serverless-twitter

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  memorySize: 128

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: GET
          path: /hello

resources:
  Resources:
    # Cognito User Pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-CognitoUserPool-${sls:stage}
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        MfaConfiguration: OFF
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-CognitoUserPoolClient-${sls:stage}
        GenerateSecret: false
        UserPoolId:
          Ref: CognitoUserPool
