org: snowcait
app: serverless-twitter
service: serverless-twitter

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
