name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - serverless.yml
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: npm install -g serverless
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::869192426624:role/GitHubActionsOIDC
          aws-region: ap-northeast-1
      - run: serverless deploy
